GOOGLE_CLIENT_ID = 'YOUR_RGOOGLE_CLIENT_ID'
GOOGLE_CLIENT_SECRET = 'YOUR_GOOGLE_CLIENT_SECRET'
DOMAIN = 'http://127.0.0.1:5000/'
SCOPE = 'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email'
APP_SECRET_KEY = '123456'
MYSQL_PASSWORD = 'YOUR_MYSQL_PASSWORD'
